### ISSUE TITLE
Add more supported PWM formats 

### ISSUE THREAD

**Issue by nictru** [nf-core/tfactivity#2]
### Description of feature

Currently only the `PSEM` (Position-specific energy motif) format is supported, which is not widely used. With the following conversion steps we could accept the more popular `JASPAR` and `transfac` formats and convert them into the `PSEM` and `MEME` format as needed. The `MEME` format will be necessary for `SNEEP`

```[tasklist]
### Tasks
- [x] `JASPAR` to `transfac` using [this script](https://github.com/SchulzLab/TEPIC/blob/master/Code/JASPAR_to_PSCM.py) (optional, only if input is provided as `JASPAR`)
- [x] `transfac` to `PSEM` using [this script](https://github.com/SchulzLab/STARE/blob/main/Code/PSCM_to_PSEM.cpp)
- [x] `transfac` to `MEME` using [transfac2meme](https://meme-suite.org/meme/doc/transfac2meme.html) which should be available in [this container](https://biocontainers.pro/tools/meme)
- [ ] Use `MEME` output in `FIMO` subworkflow
```
